theme: jekyll-theme-minimal
title: Maltyst for mautic
description: Wordpress plugin for  integration with mautic instance. The goal is to facilitate email collection and allow easy newsletter setup with mautic as a backend.
markdown: kramdown
sass:
  style: compressed
