theme: null
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Base settings
title: Maltyst for mautic
description: Wordpress plugin for  integration with mautic instance. The goal is to facilitate email collection and allow easy newsletter setup with mautic as a backend.
logo: /assets/images/logo.jpeg

include:
  - /assets/style.css

markdown: kramdown
sass:
  style: compressed


# Static assets
defaults:
  - scope:
      path: "assets/images"
    values:
      layout: "null"